CREATE TABLE satama (Kayntisatamanumero INTEGER PRIMARY KEY,
Karttalehti INTEGER,
Nimi VARCHAR(32) NOT NULL,
Palvelut VARCHAR(250) ,
Kotisivu VARCHAR(100),
ViimeksiMuokannutKayttajaID INTEGER FOREIGN KEY NOT NULL
)

CREATE TABLE chekin (ChekinID INTEGER AUTO_INCREMENT PRIMARY KEY,
KayttajaID INTEGER NOT NULL FOREIGN KEY, 
Kayntisatamanumero INTEGER NOT NULL FOREIGN KEY,
Muokkausaika TIMESTAMP NOT NULL DEFAULT GETDATE()
)

CREATE TABLE kayttaja (KayttajaID INTEGER AUTO_INCREMENT PRIMARY KEY,
Nimi VARCHAR(32) NOT NULL,
VeneenTyyppi VARCHAR(32),
VeneenNimi VARCHAR(32),
VeneenPituus INTEGER,
VeneenSyväys INTEGER
)

CREATE TABLE arvostelu (ArvosteluID INTEGER AUTO_INCREMENT PRIMARY KEY, 
Kayntisatamanumero INTEGER NOT NULL FOREIGN KEY,
KayttajaID INTEGER NOT NULL FOREIGN KEY,
Tähdet NUMERIC(5,0) NOT NULL
)


